#!/usr/bin/env bash

export CONTECO_LABEL="kafka_rest.base - ContEco"
export CONTECO_DESCRIPTION="Confluent Kafka REST image, with configuration changes."

export CONTECO_TYPE="kafka_rest"
export CONTECO_NAME="base"
export CONTECO_TAG="6.0.0"

export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="confluentinc/cp-kafka-rest:6.0.0"
